### ISSUE TITLE
Page not filling full height 

### ISSUE THREAD

**Issue by chlebta** [almasaeed2010/AdminLTE#1182] opened 2016-09-02 15:12 UTC
Hello,
I got an issue when i don't have many content in my page then it's not filling the screen and a blank space in bottom is appearing.
<img width="1280" alt="screen shot 2016-09-02 at 16 48 56" src="https://cloud.githubusercontent.com/assets/1204608/18208597/609383a4-7130-11e6-8e19-66cda3184924.png">

**Comment by dudnikgg** [comment] 2016-09-03 06:29
Hi, do you have errors in your debugger (F12)?

**Comment by chlebta** [comment] 2016-09-05 08:25
@dudnikgg  no erros in my debugger

**Comment by ashep** [comment] 2016-09-05 10:58
+1, I have the same trouble

**Comment by zburk** [comment] 2016-09-08 15:35
Can you upload your source file to look at? I've tried to reproduce not having content on the page but it still fills the entire page for me. Perhaps you missed a closing HTML tag?

<img width="1043" alt="screen shot 2016-09-08 at 11 32 38 am" src="https://cloud.githubusercontent.com/assets/5782327/18355797/47ad89fc-75b8-11e6-9320-8b0d3a56ddef.png">

**Comment by parhs** [comment] 2016-09-30 09:08
I have the same issue. I think the problem is that javascript calculation isn't correct.

https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L261

Here I think it should be 

`  if (window_height >= sidebar_height + neg) {`

**Comment by wildcat010** [comment] 2016-10-13 14:54
Hi,

I am using angular2 and I had the same problem.

I solved it by just loading the "app.js" in my AppComponent.

import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    templateUrl: 'app/app.component.html'
})
export class AppComponent {
    constructor()
    {
        console.log('preparing to load...')
        let node = document.createElement('script');
        node.src = "../scripts/app/app.js"; // you app.js script
        node.type = 'text/javascript';
        node.async = true;
        node.charset = 'utf-8';
        document.getElementsByTagName('head')[0].appendChild(node);
    }
}


Hope it helps.

**Comment by csotomon** [comment] 2016-10-13 22:50
Just add app.js to page

**Closed** 2016-11-04 15:20 UTC
Labels: Question

**Comment by duleorlovic** [comment] 2017-02-10 17:46
I can't see last sidebar link. It is easy to reproduce. Open [blank page](https://almsaeedstudio.com/themes/AdminLTE/pages/examples/blank.html), collapse **Examples** menu and manually remove content from `control-sidebar` (it is on right and populated from demo.js).
Than try to resize the window until you do not see last sidebar link.
![adminlte 2 pace page last sidebar link](https://cloud.githubusercontent.com/assets/1426092/22837491/1b741954-efc1-11e6-8b7a-f3abf584b029.png)

**Comment by ashep** [comment] 2017-02-10 20:58
+1, issue still exists.

**Comment by nothingalike** [comment] 2017-02-11 17:29
Yeah using angular 2 here. Loads fine, but when i change out the views the issue occurs. If i resize the screen the height gets fixed.

**Comment by sageprosell** [comment] 2017-12-17 12:09
+1, issue still exists when changing views

**Comment by maurizio96** [comment] 2018-01-10 21:32
+1

**Comment by abhishektomer** [comment] 2018-05-13 13:49
I am having the same problem  still no luck
https://github.com/jeroennoten/Laravel-AdminLTE/issues/206

**Comment by boussoufiane** [comment] 2018-08-02 15:17
i have the same issue with angular 6 .
do you know what is the reason of this issue and what is the solution or workround ?

**Comment by boussoufiane** [comment] 2018-08-03 09:42
Finally i fixe the problem by adding this to component : 

`declare var $:any;
$('body').layout('fix');
`
NB : i use adminlte 2.4 with angular 6

**Comment by thiagoluiznunes** [comment] 2019-05-21 01:42
I solved my problem adding this css class to my sidebar. 

```css
.skin-blue .main-sidebar {
  position: fixed;
}
```
```html
<div class="skin-blue">
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header"></li>
      <li routerLinkActive="active">
        <a [routerLink]="['/dashboard/overview']">
        <i class="fas fa-home"></i><span> Painel </span></a></li>
      <li routerLinkActive="active">
        <a [routerLink]="['/dashboard/profile']">
        <i class="fas fa-user-circle"></i><span> Perfil </span></a>
      </li>
    </ul>
  </section>
</aside>
</div>
```
