### ISSUE TITLE
User account menu fly out the screen in small screen

### ISSUE THREAD

**Issue by eruvierda** [almasaeed2010/AdminLTE#1302] opened 2017-01-03 15:26 UTC
dear @almasaeed2010 
I used your admin LTE as a foundation building my web apps school project
I found an issue that the user account menu fly outside the screen when screen is resized

![bank sampah 3](https://cloud.githubusercontent.com/assets/24892521/21612358/671bd72e-d203-11e6-8f97-e06b51f66b3d.png)

my code
```
 <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            
          <!-- User Account Menu -->
            <li class="dropdown user user-menu">
              <!-- Menu Toggle Button -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <!-- The user image in the navbar-->
                <img src="<?php echo base_url('assets/avatar/avatar_default.png');?>" class="user-image" alt="User Image">
                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                <span class="hidden-xs"><?php echo $this->session->userdata('fullname');?></span>
              </a>
              <ul class="dropdown-menu">
                <!-- The user image in the menu -->
                <li class="user-header">
                  <img src="<?php echo base_url('assets/avatar/avatar_default.png');?>" class="img-circle" alt="User Image">

                  <p>
                    <small><?php echo $this->session->userdata('fullname');?></small>
                  </p>
                </li>
                <!-- Menu Body -->
               
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-right">
                    <a href="<?php echo base_url(); ?>Auth/logout" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-custom-menu -->
      </div>
```

**Comment by almasaeed2010** [comment] 2017-01-08 17:47
Hello @eruvierda,

I tested the menu on all screen sizes but couldn't replicate the issue. Could you please provide the size that makes this issue happen?

Thanks!

**Comment by eruvierda** [comment] 2017-01-11 12:53
sorry for the delay @almasaeed2010 I'm facing midterm test this week.

its not showing  when I resized to nearly mobile phone screen size. perhaps its something wrong when I edit the code using the base template.

when I use mozilla to inspect and check the screen size, it happened below 980x1280. 
what code do i need to provide the detailed inspection?

**Comment by almasaeed2010** [comment] 2017-01-11 14:44
Unfortunately, I still couldn't reproduce the issue on FireFox even after testing it with multiple screen sizes. It could very well be something simple like missing a closing ```</div>``` or a markup error in general. It would be wise to split your components into their own ``.php``` files for example to reduce the amount of HTML markup in each page making it easier to debug. Otherwise, please provide a link to your implementation that might help us to identify your issue better.

Goodluck with your midterms!

**Comment by eruvierda** [comment] 2017-01-11 15:22
@almasaeed2010 
here is my implementation page[https://goo.gl/yN6MWa](url)

I already split it into several ```.php``` files ; header.php , dashboard.php etc. I place **user account menu** in header.php 

to access the page unit to login
this is your user name and pass
```
username : almasaeed
password : test
```

**Comment by REJack** [comment] 2017-01-11 15:42
@eruvierda Sorry that i used almasaeed's login but i found your problem 😄 

Your whole main-header structure is not correct, but you can simple fix that problem with removing the `<div class="container-fluid">` around `a.sidebar-toggle` & `div.navbar-custom-menu`

**Comment by eruvierda** [comment] 2017-01-11 16:31
I removed the ```<div class="container-fluid">``` as you suggested but the problem still occurred.
please open it using firefox under 800×1280px 

as long as I get the solution test account is no problem to be used @REJack

**Comment by REJack** [comment] 2017-01-11 17:20
i cant see a problem under 800x1280px, it looks fine for me

**Comment by REJack** [comment] 2017-01-11 17:31
I found only a problem with the user dropdown.
I would recommend it to rebuild the `<header class="main-header">`, it look not correct that should fix your problems

**Comment by eruvierda** [comment] 2017-01-11 17:38
I'll try rebuilding the ```main-header```
help I could find the problem soon.

its midnight here 💃 💃

**Comment by REJack** [comment] 2017-01-11 17:40
I hope you find it, you can update AdminLTE too your version is 2.3.7 😄

**Comment by almasaeed2010** [comment] 2017-01-14 06:44
@eruvierda,

Have you resolved your issue? If so, please let us know :)

Thanks!

**Comment by eruvierda** [comment] 2017-01-16 16:32
I still haven't resolved the problem.
very busy weekend  (moving)
I start review the code again this night.

**Comment by eruvierda** [comment] 2017-01-17 00:22
Solved : 
when I work with my pal, it seems we wrote down this code `<script type="text/javascript">
    $(document).ready(function() {
    $('.navbar a.dropdown-toggle').on('click', function(e) {
        var $el = $(this);
        var $parent = $(this).offsetParent(".dropdown-menu");
        $(this).parent("li").toggleClass('open');

        if(!$parent.parent().hasClass('nav')) {
            $el.next().css({"top": $el[0].offsetTop, "left": $parent.outerWidth() - 4});
        }

        $('.nav li.open').not($(this).parents("li")).removeClass("open");

        return false;
    });
});

  </script>`

that affect the user menu dropdown setting.

**Comment by almasaeed2010** [comment] 2017-01-17 14:46
Thanks for sharing the solution with us!

**Closed by almasaeed2010** 2017-01-17 14:46 UTC
Labels: Question
