### ISSUE TITLE
Google Map Not Show In Main Content area

### ISSUE THREAD

**Issue by githubhasib** [almasaeed2010/AdminLTE#233] opened 2015-02-07 19:08 UTC
I want to show google  map in my content area.But after using this code map not show with this templete.

```
<style>
 #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
    <script>
var map;
function initialize() {
  var mapOptions = {
    zoom: 8,
    center: new google.maps.LatLng(-34.397, 150.644)
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
    <div id="map-canvas"></div>





```

**Comment by kressly** [comment] 2015-02-07 20:05
I have tested but i think it is not a bug with the template but with the google api
Initaly i was using this for google map on one of my website. But i have just copied and pasted my own code into an empty page but it is not working there but the same code works on another of my pages. So i do not think it is a problem cause by AdminLte. Create a blank page without AdminLte and let us know whether that code worked in there.

**Comment by almasaeed2010** [comment] 2015-02-07 20:22
Does this by any chance relate to this PL #91?

**Comment by kressly** [comment] 2015-02-07 20:38
@almasaeed2010  I don't think so because i have added that months ago but still it was not working
However i have found the reason why his code was not working if of course he has done the merge from
https://github.com/almasaeed2010/AdminLTE/pull/91

@githubhasib  Your problem is due to height: 100%. Google is expecting you to add a height in pixels not in percentage

example of working code that i have tested
```
<style>
 #map-canvas {
        height: 300px;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
    <script>
var map;
function initialize() {
  var mapOptions = {
    zoom: 8,
    center: new google.maps.LatLng(-34.397, 150.644)
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
    <div id="map-canvas"></div>
```
If you copy that code i just wrote and it does not work then you should visit the issue mentionned by @almasaeed2010  and edit the file AdminLte.css and core.less

**Comment by kressly** [comment] 2015-02-09 20:40
Were you able to implement it ? If yes, can you please close this issue ? Thanks

**Closed** 2015-02-11 00:08 UTC

**Comment by CharlesOkwuagwu** [comment] 2015-04-21 15:05
This is still an issue.
Is there a way to set the content div height  to be 100% so that we can easily embed maps and other content that need to be 100% height?

**Comment by CharlesOkwuagwu** [comment] 2015-04-21 15:42
@kressly I have a blank page like so with #map height 100% and it works just fine. but once embedded in the template the #map height goes to 0px.

http://leafletjs.com/examples/mobile-example.html

This is the only css used:
`
body {
    padding: 0;
    margin: 0;
}
html, body, #map {
    height: 100%;
}
`

**Comment by zharding** [comment] 2017-07-10 21:37
Agreed, this is an issue. After reviewing the css, im still not sure where the issue is.

**Comment by ptsneves** [comment] 2019-06-22 14:25
I also have this issue.

**Comment by omargarro** [comment] 2020-10-28 12:20
hi @ptsneves , can you share a piece of code please? 
I can't still make it work. Something is quite wrong when including adminlte.min.js 
When loading my page, I get to see the map just for a millisecond, but when page is 100% loaded the map dissapears.
If I remove adminlte.min.js or even if I include it "before" jQuery file, map is shown OK (but obviously my dashboard and menu and everything from adminLTE stop working)
