### ISSUE TITLE
Mini sidebar issue on safari

### ISSUE THREAD

**Issue by iaesaudi** [almasaeed2010/AdminLTE#370] opened 2015-04-27 08:34 UTC
There is an issue with **Mini Sidebar** on safari 8.0.5 which make menu tabs have a trace after moving out from them and they will stay like this and they are non functional.

Here is an image for it:
![minisidebar_safari](https://cloud.githubusercontent.com/assets/11377260/7344030/d6154fbc-ecd0-11e4-86ea-7ce91828c554.jpg)

**Comment by almasaeed2010** [comment] 2015-04-29 22:01
Confirmed.

**Comment by almasaeed2010** [comment] 2015-04-29 22:01
I will look into it as soon as possible. This is extremely odd.

**Comment by almasaeed2010** [comment] 2015-04-29 23:25
The issue is being caused by ```overflow: visible;``` on the menu's links. If I remove the property and modify it to work properly, another issue arises, which is what we discussed in issue #209 in this [comment](https://github.com/almasaeed2010/AdminLTE/issues/301#issuecomment-89559523). I will look further into it when I have time.

**Comment by almasaeed2010** [comment] 2015-05-05 02:01
Fixed in master. I will release beta-2 soon. Thanks.

**Closed by almasaeed2010** 2015-05-05 02:01 UTC
Labels: bug
