### ISSUE TITLE
Where put page footer like `copyright 2014`?

### ISSUE THREAD

**Issue by yuomtheara** [almasaeed2010/AdminLTE#88] opened 2014-08-03 01:42 UTC
I would like to put page footer like `copyright 2014`.
where put it?
Pl example for me.

**Comment by lenamtl** [comment] 2015-01-03 13:57
Ok I see, I didn't saw this issus because my pages have a lot of content.
I will fix this and get back to you asap.

**Comment by lenamtl** [comment] 2015-01-03 14:29
Ok I see I didn't got this issue because my pages have a lot of content (more long than the menu).
I will try to found a solution. I'm not sure if this will be possible the way the pages are built.

I think the aside should be done differently or maybe we need to add another wrapper....

**Comment by kressly** [comment] 2015-01-03 14:54
Ok tks. But if u do find any solution, kindly share it will us so that we may all profit from it

**Comment by lenamtl** [comment] 2015-01-03 15:15
Of course, I will need to find a solution for my project anyhow.

**Comment by almasaeed2010** [comment] 2015-01-03 19:33
Since both the sidebar and the main content (right-side and left-side asides) are wrapped inside the wrapper. Placing the footer after the wrapper would solve your problem. That is, with a little bit of css tweaks to the footer, you will get the desired effect.

**Comment by almasaeed2010** [comment] 2015-01-03 20:07
Here is an example of how to do that. This is the HTML to add after the .wrapper div:
```html
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <a class="btn btn-primary btn-sm" href="http://almsaeedstudio.com/docs">Docs</a>
  </div>
  <strong>Copyright &copy; 2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.					
</footer>
```

Here is the CSS. The code below uses less and was placed in the core.less file.
```css
.content {
	padding-bottom: 50px;
}
.main-footer {
	background: #fff;
	padding: 15px;
	color: #444;
	height: 50px;
	border-top: 1px solid #eee;
	margin-left: @left-side-width;
	margin-top: -50px;
	&.full-width {
		margin-left: 0;
	}
}
```

Finally, add this to app.js after line 31. This will allow the footer to stretch with the wrapper.
```js
$(".main-footer").toggleClass('full-width');
```

The full sidebar toggle function in app js which starts at line 18 should look like this:
```js
	//Enable sidebar toggle
	$("[data-toggle='offcanvas']").click(function (e) {
		e.preventDefault();

		//If window is small enough, enable sidebar push menu
		if ($(window).width() <= 992) {
			$('.row-offcanvas').toggleClass('active');
			$('.left-side').removeClass("collapse-left");
			$(".right-side").removeClass("strech");
			$('.row-offcanvas').toggleClass("relative");
		} else {
			//Else, enable content streching
			$('.left-side').toggleClass("collapse-left");
			$(".right-side").toggleClass("strech");
		}

		$(".main-footer").toggleClass('full-width');
	});
```

Screenshot of the final effect:
![screen shot 2015-01-03 at 3 00 33 pm](https://cloud.githubusercontent.com/assets/1512664/5603584/2a6921d6-935a-11e4-8287-4def64ddf386.png)

**Comment by kressly** [comment] 2015-01-03 21:36
Wow,
I almost did it but i think i am missing something somewhere but i can not tell what and this is by copying and pasting the code as it is. Also for the core css is there not one } that is not right at the end ? The first } at the end closed the .main-footer { . Is the second } not an error. And even when i remove it, i still get this whether i remove it or not .

![footer](https://cloud.githubusercontent.com/assets/925132/5603844/48cddd7a-9390-11e4-9d7a-2082c0ee03d8.png)

**Comment by almasaeed2010** [comment] 2015-01-03 22:24
The css code was using LESS. which means you need to compile it first. Here is the css precompiled (so just add it in your AdminLTE.css file.

```css
.content {
    padding-bottom: 50px;
}
.main-footer {
    background: #fff;
    padding: 15px;
    color: #444;
    height: 50px;
    border-top: 1px solid #eee;
    margin-left: 220px;
    margin-top: -50px;
}
.main-footer.full-width {
    margin-left: 0;
}
```

Let me know if this doesn't work. We might need to add some extra js code.

**Comment by kressly** [comment] 2015-01-04 07:24
Wow thanks. It is better that the first one but still it is does not go completely to the end of the page.
![footer](https://cloud.githubusercontent.com/assets/925132/5605126/3f0d5f16-93e2-11e4-8ca3-6207ac27d261.png)

And also when i resize the window to check how responsive it is, i get this 
![footer_responsive](https://cloud.githubusercontent.com/assets/925132/5605137/ae36210c-93e2-11e4-9557-41e5119f4295.png)

**Comment by lenamtl** [comment] 2015-01-04 16:45
Hi,
I already tested snippet after the wrapper and it's not working properly.
The same problem occur when having a long side menu and few content.

**Comment by kressly** [comment] 2015-01-04 18:17
I don't get it well. Am i to add a class named minimum to the footer or copy the content to the existing class

**Comment by almasaeed2010** [comment] 2015-01-04 18:25
I attempted fixing this using JS but there were major issues in the layout that I have recently discovered. We are working on the next AdminLTE release and these issues are being addressed. We are not sure if the next release will be 2.0 or another 1.x yet. If the only solution we find to fix these issues will require changing the mark up of the template, we will release it under 2.0 with upgrade instructions. To get notifications about the next release and other major changes, please subscribe to our mailing list using this link 

Http://almsaeedstudio.com/#subscribe

**Comment by lenamtl** [comment] 2015-01-04 18:43
Kressly you have to add the minimum class to the main < section > 
This solution is not ideal but can do the job as a temporary fix.
Example for invoice page

```
<section class="content invoice minimum">  
```

**Comment by kressly** [comment] 2015-01-04 20:14
@almasaeed2010 Thanks I have subscribed as Max John
@lenamtl  Thanks a lot but i think that they is still something i am not getting. I have actually been working on the empty.html page of  AdminLte and I already have a class attached to section and 
[code]
 <section class="sidebar">

[/code]

So please is it to this section that i have to add the class minimum  ? Thanks a lot

**Comment by lenamtl** [comment] 2015-01-05 12:51
Hi,

No sidebar is for the sidebar you have to add it to the main content section.

```
 <section class="content">
```
change it to

```
 <section class="content minimum">
```

**Comment by kressly** [comment] 2015-01-06 06:59
@lenamtl 
I don't know whether there is something i am not doing right but i have applied the code to my page with the previous code you provided but nothing seems to be moving. Or am i to add this to the code provided by @almasaeed2010  ?
Please visit 
http://usefaith.voiedusucces.net/standard_a.php and login using
 username justfortest
And password justfortest

And after you are logged in check the footer.

**Comment by lenamtl** [comment] 2015-01-06 14:29
Hi,
First you have to place the code at the correct place now it is not well place.

If you are using my code you place the footer between < / section > and < / aside> not before < / section >.
I don't have the time to tests all your code but what I suggest you is to us my code as it is and when it's work ok then add your own css. So remove all your custom footer code and images for now...

```
</section>
        <footer>
                     <div class="row">
                       <div class="col-sm-6">
                         <p> Copyright  2014</p>
                       </div>
                     </div>
          </footer>

            </aside> 
        </div><!-- ./wrapper -->

```

Add this css in AdminLTE.css file (do not use inline css directly in your page)

```
 footer {
position: relative;
padding: 15px;
background: #FFF;
color: #000;

}

```

For the minimum class you have placed it at the correct place as you can see you have extra space at the end of the menu, you will need to adjust the px number after in the minimum css code.

**Comment by lenamtl** [comment] 2015-01-06 19:43
@kressly 
I gave up on sticky footer, no one are working correctly they all overlap content.
So I use the code I provided for now and I will let you know if I found a better solution, 
like almasaeed2010 said there is something wrong with the layout.

@almasaeed2010
Could you point us where is the problem in the layout so we can find temporary solutions.

**Comment by almasaeed2010** [comment] 2015-01-06 19:50
The problem is that the left-side is not contained within the wrapper. As a result, the wrapper only takes the height of the content and neglects the height of the sidebar. Since left-side is positioned as absolute, it's not possible to let the wrapper stretch to it's height. We are working on a solution for that. Currently we only see JS as a solution. I will get back to you if I get something new.

**Comment by kressly** [comment] 2015-01-07 12:22
@lenamtl 
I just copied and pasted your code and it worked. Thanks a lot. 
![1](https://cloud.githubusercontent.com/assets/925132/5645431/25868626-9667-11e4-8571-6cedcd8d5961.png)

@almasaeed2010 anything new will also be appreciated

**Comment by lenamtl** [comment] 2015-01-07 14:14
I'm glad you fixed it

**Comment by kressly** [comment] 2015-01-08 07:35
:+1:

**Comment by kressly** [comment] 2015-01-12 04:41
I think this one is solved right ? But the closing button is not down here or is almasaeed the only one who can close this ?

**Closed** 2015-01-12 05:50 UTC
