### ISSUE TITLE
Arrow and labels are not align in side bar

### ISSUE THREAD

**Issue by faridmes** [almasaeed2010/AdminLTE#806] opened 2015-11-25 23:00 UTC
I'm on Linux Fedora, I use Firefox 42.0 and on the left side bar, the arrow and the labes are not align with the text.

I attach a screenshot to display the issue.

![template_bootstrap](https://cloud.githubusercontent.com/assets/1018814/11411485/afa9f4c0-93d0-11e5-990b-bfbf9ddab819.png)

**Comment by gbaudoin** [comment] 2015-11-26 08:45
Same results with Firefox 42.0 on Mac OS X. The pull-right {float: right} of font-awesome && bootstrap make it go down a bit.

**Comment by gbaudoin** [comment] 2015-11-26 08:55
Duplicate of #752 , fixed in version 2.3.2

**Comment by almasaeed2010** [comment] 2015-11-26 15:17
Upgrade to v2.3.2 please. The preview wasn't upgraded until now. It should work fine if you test again.

Thanks!

**Closed** 2015-11-28 18:36 UTC
Labels: Duplicate, Question
