### ISSUE TITLE
AdminLTE 2.1.0

### ISSUE THREAD

**Issue by almasaeed2010** [almasaeed2010/AdminLTE#301] opened 2015-03-23 14:52 UTC
The progress in AdminLTE v2.1.0 has begun and I would appreciate your feedback along the way. 
The first step was to create the sidebar mini which has been long awaited for.

![screen shot 2015-03-23 at 10 41 55 am](https://cloud.githubusercontent.com/assets/1512664/6782248/4cb4b480-d149-11e4-8766-2c1dc83c59b5.png)

Updates about the progress will be posted here until we are ready for alpha. 
Here is test url https://almsaeedstudio.com/themes/AdminLTE-dev/index2.html <- this url will only work until alpha is ready.

Known issues with sidebar mini:
1- Can't be used with fixed layout. This is because SlimScroll requires ```overflow: hidden``` wrapper on the sidebar. (I am not sure if we can fix this since I tried several times but it didn't work but if you have a solution don't hesitate to let me know).
2- Labels don't appear correctly. (should be fixed soon).
3- An issue we can't fix but we should make the users aware of is that the logo must have two variants. A "logo-mini" and "logo-lg" for collapsed and non-collapsed respectively, producing:
```html
<a href="/example" class="logo">
  <!-- mini logo for sidebar mini 50x50 pixels -->
  <span class="logo-mini"><b>A</b>LTE</span>
  <!-- logo for regular state and mobile devices -->
  <span class="logo-lg"><b>Admin</b>LTE</span>
</a>
```

Sidebar mini is an optional feature. It can be activated by adding the class ```.sidebar-mini``` to the body tag. We also created a separate .less file for it. This way the user gets to comment it out form the main LESS file when it is absolutely not needed.

Note: please use this post only for reporting bugs and suggestions for v2.1.0.

**Comment by YasserHassan** [comment] 2015-03-23 17:37
Great progress, congratulations @almasaeed2010.

With the introduction of v2.1, I suggest moving the search form the top menu. The current location in the sidebar does not make it handy for use. If you are a user who prefers the hidden/mini sidebar and you need to search for something, you need to expand the sidebar, enter something and search, then collapse the sidebar again. This is three steps instead of one. Imagine if you need to search a lot! Not streamlined from a usability point of view. Search boxes better be always visible and accessible.

Also keep in mind the mobile screen version, the search form could be stacked under the title and the menu or converted to an icon that expands to a full search input or popup dialog.

**Comment by adaniello** [comment] 2015-03-23 17:46
@almasaeed2010 simply great!

+1 "search form the top menu"

i was thinking: why not add a media gallery/file explorer (starting by attachments blocks in mailbox ".mailbox-attachments")? or integrating a good plugin http://www.responsivefilemanager.com/

**Comment by kressly** [comment] 2015-03-23 18:01
@almasaeed2010 thanks for all the great work. However I would have suggested the side bar mini to be for a right side bar. In other word possibility to keep the formal side bar and have the right side bar minified. However since it is optional, glory be to God. 
Now please I u can add a drop down search button somewhere at the top ..
To me the search field is one of the most important thing needed. In the previous version it was placed on the left side bar and the problem is that if someone visits the website with his mobile he may not know that there is a search field there. Therefore if we can hav a search field like facebook on mobile that will be great

**Comment by almasaeed2010** [comment] 2015-03-23 18:02
@YasserHassan I noticed the issue and I thought about using a feature that AdminLTE already provides which is a search form in the navbar. However, that also has its limitations. In small devices, it is difficult to make space for all of that in the navbar. The best soution I could think of is this:

![screen shot 2015-03-23 at 1 54 20 pm](https://cloud.githubusercontent.com/assets/1512664/6786665/251ec030-d164-11e4-9c09-deee7c456e48.png)

Now, that will work but the breadcrumbs have to go. I tried adding them in a new line but it just didn't look good. So, until now, keeping the search form in the sidebar is our best bet. Nonetheless, if I find a fix that I am capable of implementing, I will for sure give it a try.

@adaniello That's a nice plugin but we are using Bootstrap WYSIHTML5 and I am not sure if it's compatible with it. I will look into it and if it is possible I might add it in the todo list for a future release. 

Currently, for 2.1.0, we want the sidebar mini, right sidebar, and light sidebar skin. We'll always add more plugins and features as we go on.

Thank you for the feedback. Please keep it up!

**Comment by almasaeed2010** [comment] 2015-03-23 18:06
@kressly I understand your concern. However, think of it this way, if the user can't find the search form then he can't navigate the site to begin with. I mentioned a couple of things about that in my previous post. I will keep working on finding a solution. Thank you!

**Comment by YasserHassan** [comment] 2015-03-23 18:55
@kressly the mini sidebar makes more sense as it is now in the preview above. It's the intermediate state between the fully expanded and the hidden states that preserves the sidebar navigation functionality without occupying too much space especially in medium screen sizes. The right sidebar suggested earlier was for extra information that needs a relatively large space to display so replacing it with a mini sidebar would probably be good form a usability point of view unless you have another navigation or menu at the right.

@almasaeed2010 you do not need to move the search form to the breadcrumbs area. Besides my previous suggestions of stacking the search on mobile screens under the menu on a 3rd line or converting it to an icon that expands or launches a search popup dialog box, I am adding another suggestion, converting the menu search on mobile screens to a search icon in the top menu (beside the messages icon) that shows/hides the 3rd search line when clicked. We have like 3 alternatives for the search functionality that make it usable on all screen sizes.

**Comment by almasaeed2010** [comment] 2015-03-23 19:45
I must have misunderstood you. I'll see what I can do about that soon. I'll report any progress back here.

**Comment by laudeco** [comment] 2015-03-24 08:52
@almasaeed2010 Super work ! thanks
When the sidebar is in mini, it could be very interesting to expand the multilevel menu on hover instead by click like now. On mobile of course, we keep the click to expand.

Thank you !
Kind

**Comment by YasserHassan** [comment] 2015-03-24 09:15
@almasaeed2010 thank you for your consideration. In addition to the above, many mobile apps like Facebook's and LinkedIn's handle the search functionality in a streamlined way that does not clutter the user interface while keeping the search accessible. They can be good starting points to brainstorm this area which in my opinion is a weakness point in this great design.

**Comment by almasaeed2010** [comment] 2015-03-24 12:03
@laudeco that sounds good. I will try it as an experiment and see how it goes.

@YasserHassan these companies don't use responsive design. What'd I'd like to do is to have only one search form instead of implementing it twice (in sidebar and navbar for example). So, if I could modify the current design to be easily accessible from the sidebar, it would be ideal. The idea I have is to replace the form with a search icon in the mini sidebar. On hover, the form would appear and stay open until a click outside the form container occurs (along side with keyboard event listeners like enter or esc).

**Comment by YasserHassan** [comment] 2015-03-24 20:22
@almasaeed2010 I know that the examples I mentioned are not responsive designs, they are mobile apps after all. What I meant was to see how those apps make the search functionality accessible and streamlined from a user's point of view, then see how to make it happen in AdminLTE as from a layout perspective, the mobile apps is comparable to the small version of AdminLTE and their application of the search functionality is more intuitive.

**Comment by kressly** [comment] 2015-03-24 22:24
@almasaeed2010 I most at time on Facebook with my mobile However I do not really use their left menu because most thing that i need are either on the top or displayed directly there. On mobile devices, the left menu is closed by default. So for a beginner (a new user) he may not know how to open that menu. In my case and i think also in the case of Facebook most important things are either on the top menu. Facebook also use to put the search on the menu (left) but lately they have moved it to an icon on the top just like the message box that we have on AdminLte only that when you click on the search icon the menu drops down with the search field.

@YasserHassan My problem is that most people make the left side bar menu as the main menu and most users are expecting a left side bar menu more than the right. Now when the side bar is reduced to icon like in the image above, the user must now guess the meaning of every icon and for a new user, he may be afraid of clicking. For example I personally do not even know the meaning of these icons
![1](https://cloud.githubusercontent.com/assets/925132/6814200/71f6b136-d274-11e4-9199-0466fc30b194.png)

But If I were to have a link made of Icon with a text, it will be more easier for me to click. How much more for a new user who may be on an accounting website or a sensible website.

**Comment by YasserHassan** [comment] 2015-03-24 23:16
@kressly The mini sidebar is an convenient middle ground between a completely hidden and fully expanded sidebar. This mini state is user-optional and of course is not meant for new system users until they become familiar with the meaning of the icons which usually takes a very short time to grasp.

It's normal that you don't know the meaning of the icons above as this is a template and you don't use it regularly but if it is used for an application that you use on regular basis, you'll appreciate such unobtrusive mini sidebar.

Add to this that there are additional ways to add more clarification to the mini sidebar if required such as icon tooltips and fully expanding the sidebar on mouse hover.

**Comment by goof03** [comment] 2015-03-25 13:52
Hi ! It would be cool if the new version could be more requireJS aware. Where we could put all your stuff in a vendors/module directory of a new app. create an AdminLTE-config.js and call an AdminLTE.js module. I use it with backbone.js View and need many work on each update and dispatch all your file inside my apps. But thanks it's a great theme anyway ;-)

**Comment by almasaeed2010** [comment] 2015-03-25 22:57
@goof03 I am not very familiar with RequireJS and Backbone.js. So, I don't think v2.1 would provide such support. However, it is good that you have pointed this out. I will look into it more and perhaps implement a solution in future releases. Thank you for contributing!

**Comment by goof03** [comment] 2015-03-25 23:33
Just to clarify you dont have to be familiar with Backbone.js if you make your theme require.js compliant it could be use simply in many other javascript framework like angular.js, backbone.js, etc…
And more, require.js could simplify your work with your plugins dependencies, minifying your code.
Another thing come into my mind is there a reason to not using CDN for jquery and boostrap ? because if you follow Google PageSpeed advice it better to load file from many cdn than the same domain for latency, caching and parralelism. A better explanation : 
http://encosia.com/3-reasons-why-you-should-let-google-host-jquery-for-you/

**Comment by almasaeed2010** [comment] 2015-03-26 01:14
@goof03 intersting! I want to keep the page load and dependencies to a minimum. Since, not everyone uses RequireJS or similar scripts, how do you suggest we provide support without having to actually use it in the template?

I understand how the use of CDN could be beneficial. However, many users complained about them since they require offline support. This template is being used in a few NodeJS apps that work offline (which I think is awesome, btw). For that reason, I am trying to lower the usage of CDNs when unnecessary. Wouldn't you agree?

**Comment by scottscreations** [comment] 2015-03-26 01:43
I prefer the non CDN. My application could easily be put offline and on an internal limited network for security reasons.

**Comment by goof03** [comment] 2015-03-26 02:38
I don't want to feed the troll i will continue to modify the theme with CDN ;-). It's two face of the same coin …

For require.js my advice is to read the documentation and make your own choice … But it's only 14.9k and it load js only when it's need. With r.js you can create just one js file minified with just one command line for exemple you can automate this optimisation when you push a production version of your project. It's more clearer when you aggregate many library and many javascripts files from the web. It avoid to have many <script src="script1.js"></script> line in your index.html.
you create your dependencies tree and you forget it when you call a module and when you launch optimization of all your project. 
But i'm not a require.js Ayatollah there is other library to do the same thing.
RequireJS is a way to have the code organized and it avoids to use libraries without previous dependency.

**Comment by kressly** [comment] 2015-03-26 09:13
@almasaeed2010  @YasserHassan 
Yes I think tooltip and especially fully expanding the bar on mouse over will be great. However none of these will work on mobile, therefore on mobile the user will have to take a leap of Faith and click... Hum... I am just concern about new users

**Comment by kasperhartwich** [comment] 2015-03-26 09:50
I will, again, request an example of a  'data' page where a lot of information would be, like the Facebook about page.

**Comment by kressly** [comment] 2015-03-27 14:00
:+1:  @kasperhartwich 
I greatly would like to suggest that app.js and other javascript code in AdminLte to come, will be with a jquery noconflict mode in other word, instead of using $ as variable, it will be wonderful to directly user jQuery as variable.

example 
instead of ` $('#messages_content').` we can have ` jQuery('#messages_content').`

That way most people using other libraries like me will not face much difficulties and will not need to open app.js and apply some patch here and there.

@almasaeed2010  you are the best. Hope you know that :+1:

**Comment by scottscreations** [comment] 2015-03-27 20:42
http://stackoverflow.com/questions/4811807/hidden-sidebar-that-shows-up-on-hover

would something like this compliment the sidebar small nav?

**Comment by almasaeed2010** [comment] 2015-03-28 15:07
### Light Sidebar Preview

**Fully expanded**
<img src="https://cloud.githubusercontent.com/assets/1512664/6881543/d17c0be8-d539-11e4-8f49-25573c66cfb1.png" width="300" height="auto" alt="AdminLTE light sidebar color"/>

**With sidebar mini**
<img src="https://cloud.githubusercontent.com/assets/1512664/6881542/cb042d18-d539-11e4-9de2-5151ce58c8ea.png" width="300" height="auto" alt="AdminLTE light sidebar color"/>

**Comment by YasserHassan** [comment] 2015-03-28 15:24
@almasaeed2010 looks good. It would look better if the bar's right vertical edge is not obscured by the 2nd-level menu in the area shown below so the menu looks sticking beside the bar instead of above it.
![mini-toolbar](https://cloud.githubusercontent.com/assets/9349772/6881619/1728066c-d56f-11e4-9492-8ef610461fa0.png)

**Comment by almasaeed2010** [comment] 2015-03-28 15:34
@YasserHassan thanks for pointing that out

![screen shot 2015-03-28 at 11 33 36 am](https://cloud.githubusercontent.com/assets/1512664/6881639/5056b90a-d53e-11e4-855f-55bd2bd1355b.png)

**Comment by YasserHassan** [comment] 2015-03-28 16:29
@almasaeed2010 thank you for the quick response.

**Comment by almasaeed2010** [comment] 2015-03-28 18:13
### Right Sidebar

Currently only available in dark skin. The sidebar will be implemented with two show options, a slide over content options and stick option. The first will take the effect as seen below. The second will move the content to make space for the sidebar. This feature hasn't been implemented yet. We will provide it with the beta release.

![screen shot 2015-03-28 at 2 09 16 pm](https://cloud.githubusercontent.com/assets/1512664/6882246/7ac039e4-d554-11e4-8005-0e26d6bcd6f2.png)

**Comment by almasaeed2010** [comment] 2015-03-29 00:35
The [preview](https://almsaeedstudio.com/themes/AdminLTE-dev/index2.html) has been updated to reflect the new changes. Please be advised that only Dashboard 2.0 has right sidebar.

**Comment by kressly** [comment] 2015-03-29 11:42
:+1:  Wonderful
But please let lower the well that enables to choose skins otherwise it makes it difficult to click on the right side bar.
![01](https://cloud.githubusercontent.com/assets/925132/6885278/a6104564-d610-11e4-9940-f6d3257a62af.png)


And please let us have an option so that those who wants the left side bar to be completely displayed by default on large screen and only reduced when the user clicks it will still have that.

Personally I loved the white skin at the left that you show in the first image and if we can have a white skin for the right side bar, it will be good

Thanks

**Comment by YasserHassan** [comment] 2015-03-29 12:12
@almasaeed2010 looks very good. Here are some suggestions to think about:
- An option to integrate the right sidebar in the main area like the left one instead of hovering. This can be particularly useful when used on big screens to display frequently updated information that the user likes to keep an eye on without obscuring the main content or prevent interaction with it.

- The opposite for the left sidebar, an option to make it hover like the right one.

**Comment by pakey** [comment] 2015-04-01 08:25
hey，how can i use Light Sidebar  in 2.0.*

**Comment by yufieko** [comment] 2015-04-01 21:11
I found out little error in avatar size when activated the mini sidebar. 
I'm using the latest Firefox browser, in Chrome it's fine.
![capture-adminlte](https://cloud.githubusercontent.com/assets/7820512/6952672/20f2c556-d8ee-11e4-846f-ae6b0710dc18.png)

**Comment by almasaeed2010** [comment] 2015-04-01 21:13
@yufieko I noticed this issue yesterday and am trying to figure out why is it happening. I will let you know once it is solved. Thanks for keeping me informed!

**Comment by almasaeed2010** [comment] 2015-04-01 21:14
@pakey the light skins have not been implemented yet. It is a work in progress. And will be available only in v2.1.0 and above.

**Comment by pakey** [comment] 2015-04-02 00:23
@almasaeed2010 okey,3q.I'm looking forward to the arrival of the 2.1.0 version, what can I do, to make 2.0.1 earlier put into production environment.

**Comment by boolie** [comment] 2015-04-03 15:54
@almasaeed2010 @yufieko At a glance, it looks like you can fix the mini-sidebar avatar issue in Firefox by adding a 100% width to the collapsed sidebar user panel image.  I haven't tested it in IE/Chrome, but one of the following should do the trick in FF.  Cheers.

````css
/* set 'width: 100%' on the collapsed sidebar user panel image */
.sidebar-mini.sidebar-collapse .main-sidebar .user-panel img {
    /*max-width: 100%;  >>> might be able to get away without this assignment  */
    height: auto;
    width: 100%;  /*added*/
}
````
Or here...

````css
.user-panel > .image > img {
    width: 100%;  /*changed from 45px*/
    height: 100%;  /*changed from 45px*/
    max-height: 45px;  /*added*/
}
````
Or via less...

````less
 //Sidebar user panel
.user-panel {
  padding: 10px;
  .clearfix();
  > .image > img {
    width: 100%;
    height: 100%;
    max-height: 45px;
  }

 ````

**Comment by almasaeed2010** [comment] 2015-04-04 00:47
### Static Right Sidebar
Added the ability to disable slide over content.
![screen shot 2015-04-03 at 8 34 33 pm](https://cloud.githubusercontent.com/assets/1512664/6990727/27b3a55a-da41-11e4-9768-c6eacd64ca06.png)

Fixed bugs:
- Sidebar mini user image out of bounds as mentioned by @yufieko 
- Nested box widgets collapse and open issue #321 
- Added new skins and control sidebar options to demo menu

You can now review changes in Master branch and [preview the demo here](https://almsaeedstudio.com/themes/AdminLTE-dev/index2.html)

**Comment by kressly** [comment] 2015-04-04 11:39
Wow :+1: Impatienly waiting for the download link. This is awesome. Can we add something like friedns online (like facebook's own ) on the right side bar  ?

**Comment by YasserHassan** [comment] 2015-04-04 12:09
@almasaeed2010 the option to embed the right sidebar is very good. I would be better if the sidebars change is unified, either both dark or both light. It would be good too to add right sidebar to the skins thumbnails in the options settings form.

**Comment by YasserHassan** [comment] 2015-04-04 12:27
There's an issue in the left sidebar expansion behavior. I does not exactly reverse the collapsing steps so at a certain point during expansion, content that's supposed to appear only after expansion is complete is shown during the transition leading to an undesired effect as shown below.
![l-sidebar-expanding](https://cloud.githubusercontent.com/assets/9349772/6992560/f48fe244-dade-11e4-9526-584f85f9f2fb.png)

**Comment by almasaeed2010** [comment] 2015-04-04 16:45
@kressly thanks :+1: You can download and test the master repo since I updated it. Just keep in mind that it isn't ready for production yet.

@YasserHassan the right sidebar will have two different skins with the release of beta. However, it won't be affected by skin classes. It will have its own color scheme class. This is so the user can have each sidebar a color if they want. I actually like having the control sidebar dark with light skin. It all comes back to preferences and I'd like to keep the options open. Since the skins don't affect the right sidebar colors, I will add an option to the demo menu to toggle between light and dark colors instead of showing that in the skins section. I will also update the demo menu to look more appealing and position it at the bottom of the page instead of top right.

I know the effect might be a bit annoying but that's the result of having transitions added to the sidebar. I attempted to fix this several times but it comes back to js solutions or animation. The js solution will add unnecessary overhead on the browser and animation is not supported on all browsers. I will try to find a CSS based solution, which would be ideal. Thanks for reporting this.

**Comment by almasaeed2010** [comment] 2015-04-04 16:57
**Issue:** right sidebar doesn't work with boxed layout.

![screen shot 2015-04-04 at 12 56 28 pm](https://cloud.githubusercontent.com/assets/1512664/6993669/08b420f6-daca-11e4-9712-1e5dba9e60f7.png)

**Comment by YasserHassan** [comment] 2015-04-04 17:06
@almasaeed2010 
- Having the option for color each sidebar separately is even better.
- If the only solution for the the expanding sidebar issue above is JavaScript with some overhead, I vote for it. I don't think overhead would even be a problem with today's computers.
- I suggest that you add a 3rd tab to the right side menu. I know developers can add them easily but it'd be better to make sure it's done by you to make sure there are not unexpected issues, then reduce by the developer to 2 or 1 tab if required.

**Comment by ChristianWeyer** [comment] 2015-04-07 14:52
FYI: The expanding left sidebar issue currently is a blocker for even demo'ing it to customers.
A solution would be nice.

**Comment by YasserHassan** [comment] 2015-04-07 15:22
@ChristianWeyer I agree it's an important issue.
@almasaeed2010 there are a couple of templates out there similar to AdminLTE in the mini sidebar regard and they work smoothly. I don't think AdminLTE will have a problem if adopted their development approach to the mini sidebar.

**Comment by almasaeed2010** [comment] 2015-04-09 23:34
## AdminLTE 2.1.0 Alpha has been released
- Fixed sidebar mini overflow issue.
- Fixed right sidebar + boxed layout issue
- Added demo menu to right sidebar by creating a third tab (one of @YasserHassan's suggestions and to provide responsive support as @kressly suggested) 

**Release notes can be found in the [releases section] (https://github.com/almasaeed2010/AdminLTE/releases/tag/v2.1.0-alpha-1)**

**Closed** 2015-04-11 23:18 UTC
Labels: News

**Comment by kressly** [comment] 2015-04-14 09:11
Wow. Just saw this. @almasaeed2010 you are the best ! :+1:  :+1:

**Comment by GKolmerer** [comment] 2015-06-10 16:28
How i can deactivate the sidebar transition?

**Comment by diegoscor** [comment] 2015-09-16 14:50
@goof03  i've just read your comments and thought you may be able to help me. I'm new at front end developing, and I've chosen to use Admin LTE since it's a really nice template, but using Backbone.js and RequireJS. I've encountered myself with several issues since I don't completely undertand how to adapt this html template to those librarys. For example UI stopped working after I implemented require, I think it's related to a problem with the javascript, do you have any idea why this could be happening? thx!

**Comment by schekin** [comment] 2016-07-18 15:39
![2016-07-18 18 35 17](https://cloud.githubusercontent.com/assets/1081364/16920551/c355c1f2-4d16-11e6-8609-edcbeb197735.png)

add AdminLTE to rails app with gem 'rails-assets-adminlte', (then download 2.3.5 from source), i have this trouble...

**Comment by iqrajabeen** [comment] 2017-07-08 07:50
premium theme logsout when opening in mobile and clicking on any link why kindly tell me...

**Comment by molorane** [comment] 2017-10-10 11:06
Hello sir, i am currently using your template(version 2.3.3) for my admin console. I am running it on apache PHP 7. However, i noticed that when try to view it on the browsers for mobile devices and tablets, it looses the styles. The page appears as though there are no style sheets applied to the them. I am wondering why this happens and would like to get help. I tried to allow javascript on the privacy settings for the browsers of the mobile devices but that didn't solve the problem. will waiting to hear from you.
