### ISSUE TITLE
Bower TypeError: Invalid Version: 2.1.0a

### ISSUE THREAD

**Issue by yajra** [almasaeed2010/AdminLTE#338] opened 2015-04-15 03:10 UTC
Hi,

Having problem installing the template using bower and the errors are:

```
Stack trace:
TypeError: Invalid Version: 2.1.0a
    at new SemVer (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:273:11)
    at compare (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:460:10)
    at Object.neq (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:224:56)
    at GitHubResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js:131:53)
    at _fulfilled (/usr/local/lib/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/bower/node_modules/q/q.js:108:17)
```

I think it's because of version `2.1.0a` is not a proper semantic version? Just a guess as I am not a bower expert. Maybe you should use `2.1.0-alpha` or just remove the `a` on `bower.json`?

Thanks!

**Comment by almasaeed2010** [comment] 2015-04-15 22:09
Hello,
Thanks for reporting this. It should be fixed now.

**Closed by almasaeed2010** 2015-04-15 22:09 UTC

**Comment by yajra** [comment] 2015-04-16 00:26
Thanks, Issue fixed for v2.0.5. However, I was planning to use the master version (v2.1.0-alpha) on bower and I think it should be doable on master branch?

**Comment by almasaeed2010** [comment] 2015-04-16 00:46
You should never use not production ready releases because I might change some of the code without any notice. However, with a production release such as v2.1.0, changes are permanent, supported and ships with a set of upgrade instructions.

**Comment by yajra** [comment] 2015-04-16 01:01
Yes I'm aware of that. But I will use the alpha version for my experimental project too :). And will be able to update that easily once the stable version is released.

**Comment by almasaeed2010** [comment] 2015-04-16 01:48
I see what you mean. Does Bower provide a way to request a specific version like what composer does?

**Comment by yajra** [comment] 2015-04-16 01:55
Yes, like composer, bower has `bower.json` and you can specify the version you want to use.

```json
{
  "dependencies": {
    "admin-lte": "~2.0.5"
  }
}

```

I think the issue was due to invalid semver as I stated above and I guess it should be fixed by using `2.1.0-alpha`. But I'm not really sure about this because i'm also new on bower.

**Comment by almasaeed2010** [comment] 2015-04-16 02:01
I am new with bower too. I tried requesting 2.1.0-alpha but bower refused to install it. I am not sure about letting bower install an unstable version by default. I'll look into it tomorrow.

**Comment by yajra** [comment] 2015-04-16 02:02
Thanks! Btw, you also need to tag the new alpha release for it to work.

**Comment by almasaeed2010** [comment] 2015-04-16 02:05
The tag is available. However, it is tagged as a prerelease so maybe that's why bower won't allow to request it.

https://github.com/almasaeed2010/AdminLTE/releases

**Comment by yajra** [comment] 2015-04-16 02:08
Yes, but the committed `bower.json` on that release uses `2.0.1a` which is not a proper semantic version and does not exists on your tags which may have cause the issue.

**Comment by almasaeed2010** [comment] 2015-04-16 02:10
It was, true. Now however it uses 2.0.5 which is the latest stable version.

**Comment by almasaeed2010** [comment] 2015-04-16 02:11
Do you mean within the alpha release itself?

**Comment by yajra** [comment] 2015-04-16 02:12
Yes, the release itself have an invalid `bower.json` which is why I suggested to add a new tag for it to work.

**Comment by almasaeed2010** [comment] 2015-04-16 02:15
That could be the cause. I will release 2.1.0-beta after testing it tomorrow and I will make sure it has the proper tags within bower.jon and the other similar files.

**Comment by yajra** [comment] 2015-04-16 02:16
great! thanks and sorry for the hassles. :beers:

**Comment by almasaeed2010** [comment] 2015-04-16 02:17
Not at all. Thank you for helping me figure out the issue.

**Comment by almasaeed2010** [comment] 2015-04-16 15:49
Ok so this command now works with beta
```
bower install admin-lte#2.1.0-beta
```

**Comment by yajra** [comment] 2015-04-17 00:10
Fixed thanks! however this is the command that I used for it to work. Command above does not work for me.

`bower install https://github.com/almasaeed2010/AdminLTE.git#2.1.0-beta`
