### ISSUE TITLE
Changing User Account Menu Button from btn-default zo btn-danger

### ISSUE THREAD

**Issue by masteradhoc** [almasaeed2010/AdminLTE#477] opened 2015-06-01 09:28 UTC
Hi @almasaeed2010 

I wanted to change the Button of User Account Menu from btn-default zo btn-danger (in user-footer)
This works correct in full desktop view, but not in the view of a smaller windows. Please see attached. Also i cleared the cache and tried in several browsers (IE10 and FF 38)

Thanks
![workscorrect](https://cloud.githubusercontent.com/assets/6242098/7910016/48b79d68-0851-11e5-96c2-2ae3da577cbf.png)
![worksnotcorrect](https://cloud.githubusercontent.com/assets/6242098/7910017/48d5aed4-0851-11e5-8cc6-24af06591e4e.png)

**Comment by almasaeed2010** [comment] 2015-06-01 10:15
Hello,
That's caused by Bootstrap's default config for links within the navbar. I'll see if there is a fix for this issue without rewriting each button's style.

**Comment by masteradhoc** [comment] 2015-06-01 10:41
Thanks!

**Comment by almasaeed2010** [comment] 2015-08-16 20:27
This is not possible to fix without making rules for every button type because Bootstrap makes navbar links' color difficult to override. It would require too many lines to address all screen sizes. Your best bet is to add a custom css style of your own.

I apologize for the long delay (been really swamped). Thanks!

**Closed by almasaeed2010** 2015-08-16 20:27 UTC
Labels: Bug, css
